### ISSUE TITLE
Checking checkbox returns error

### ISSUE THREAD

**Issue by Aebel-Shajan** [Jean-005/Capstone_Project#49]
Error: 

```
setCompletedOrders is not a function
TypeError: setCompletedOrders is not a function
    at handleCheckedOrders (http://localhost:3000/static/js/bundle.js:484:5)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:44602:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:44646:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:44703:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:44717:29)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:48860:7)
    at processDispatchQueueItemsInOrder (http://localhost:3000/static/js/bundle.js:48886:11)
    at processDispatchQueue (http://localhost:3000/static/js/bundle.js:48897:9)
    at dispatchEventsForPlugins (http://localhost:3000/static/js/bundle.js:48906:7)
    at http://localhost:3000/static/js/bundle.js:49066:16
```

**Comment by Tommybui28** [comment]
Add missing setCompletedOrders prop from Orderlist.jsx down to Order.jsx. This led to the error where ticking one box, ticks all of them. To fix, remove use for states of checkbox, as we only have one state for all the checkboxes.
